<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>Article name</th>
        <th>Author</th>
      </tr>
    </thead>
    <tbody>
        <?php
       foreach ($articles as $article) { ?>
           <tr>
            <td>  <a href='/article.php?id=<?php echo $article -> getArticleId(); ?>'><?php echo $article -> getPostTitle(); ?> </a></td>
            <td> <?php echo $article -> getAuthor(); ?> </td>
           </tr> 
       <?php }?>
    </tbody>
  </table>
</div>
