<div>
 
<table style="width: 100%">
    <tr>
        <td><h2>Manage Categories</h2></td>
        <td style="text-align: right"><h2><a href='../Createcategory.php'>Create New Category</a></h2></td>
    </tr>        
</table>
    
<?php if (empty($Category)): ?>
    <p>No Category found.</p>
<?php else: ?>
    <table style="width:100%">
        <tr>
            <th hidden="true">Category Id</th>
            <th>Category Name</th>
            <th>Category Description</th>
            <th>Created On</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        <?php foreach ($Category as $categories): ?>
        <tr>
            <td hidden="true"><?php echo $categories->getcategoryId() ?></td>
            <td><?php echo $categories->getName() ?></td>
            <td><?php echo $categories->getCategoryDescription() ?></td>
            <td><?php echo $categories->getCreatedOn() ?></td>
            <td align="center"><?php echo '<a href="Createcategory.php?ops=Edit&Id='.$categories->getcategoryId().'">EDIT</a>'; ?></td>
            <td align="center"><?php echo '<a href="Createcategory.php?ops=Delete&Id='.$categories->getcategoryId().'">DELETE</a>'; ?></td>
        </tr>
        <?php endforeach; ?>        
    </table>
<?php endif; ?>    
</div>

